server:
  port: 9008
spring:
  application:
    name: tensquare-user #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cdb-2i9k2eti.bj.tencentcdb.com:10036/tensquare_user?characterEncoding=utf-8
    username: root
    password: abc123456
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.167.130
  rabbitmq:
    host: 192.168.167.130